### PR TITLE
Some enhancements and improvements

### PR DESCRIPTION
**Pull request by soef**
- now using a dynamic event object with getter, so some fields are only calculated or loaded if needed.
- added tests for regexp pattern compare functions

### CODE REVIEW

**Comment by soef** [comment]
Oh, node Version 0.12 fails. 

Is it really still necessary to support node.js 0.12? If, I will try to find a solution that does not go badly for the users with the recommended node Version.

**Comment by Apollon77** [comment]
In general we already decide to throw 0.12 away and with latest js-controller/admin versions also a "compatible node versions are 4,6,8" notofy will appear to all users.
So I will discuss this with @GermanBluefox after his vacation

**Comment by soef** [comment]
Please restart the test Jobs. On my side all Tests are green.

**Comment by Apollon77** [comment]
Tests on Appveyor can be ignored because was from the times where they had big problems. I can confirm tests are green.
One question: The "enhancements and improvements" are mainly for the new "on/subscription" logic, or does it affect other topics too!?

**Comment by soef** [comment]
Yes, they are mainly for the new on/subscription logic. But they also fix a few rare Errors of the old logic. For example, if there are two subscriptions for one state. The new methods are better readable, more powerful and more efficient.

**Comment by Apollon77** [comment]
Thank you!

**Pull request merged**
