### PR TITLE
Update sandbox.js

### PR DESCRIPTION
**Pull request by SliX185**
#536 fixed exclamation mark position

### CODE REVIEW

**Comment by GermanBluefox** [comment]
NO it is wrong. 
it is linke `(false instanceof Date)`

**Comment by GermanBluefox** [comment]
What happens if you use `log({a: 1, b: 2})`

**Comment by SliX185** [comment]
Jep, sorry you're right....
`[object Object]`
but GMT don't work with `!(msg instanceof Date)` anyways

**Comment by GermanBluefox** [comment]
Which log do you trying to print out?

**Comment by SliX185** [comment]
`const datum = new Date();

log(datum);`
should be like:
script.js.common.Test.Dachrinnenheizung_Test: Mon Apr 20 2020 16:56:02 GMT+0200 (GMT+02:00)

**Pull request closed without merging**
