### PR TITLE
Upgrade editor support to TS 4.4, update typings to infer object types

### PR DESCRIPTION
**Pull request by AlCalzone**
This PR updates the editor and compiler to support TypeScript 4.4. Most notably, this allows us to infer object types from object IDs. For example, the editor knows that the object with the ID `"system.adapter.javascript.0.alive"` must be a state:
grafik
The `common.alias` property is now also supported, among many others:
grafik

Inferring the type works for a bunch of common IDs. When it is not certain like in this case:
grafik
accessing properties that could exists on any of the possibilities is now allowed (but no syntax help):
grafik

fixes: https://github.com/ioBroker/ioBroker.javascript/issues/838
fixes: https://github.com/ioBroker/ioBroker.javascript/issues/846
fixes: https://github.com/ioBroker/ioBroker.javascript/issues/865

### CODE REVIEW

**Comment by AlCalzone** [comment]
Additionally, we could think about extending this functionality to `setObject` and `extendObject`, but I fear this will break (TS) or add warnings (JS) to a ton of scripts.

**Comment by PeterVoronov** [comment]
Looks awesome!

**Comment by GermanBluefox** [comment]
LGTM

**Comment by uwe72** [comment]
i still don't know how to fix my problem:
https://forum.iobroker.net/topic/52907/create-alias-in-typescript?_=1645899885876

Can anybody help me pls?

**Comment by uwe72** [comment]
> Stop spamming every issue please. Ask in the forum.

There are not answers in any issue. Hard to understand for me that i cannot ask here this question. as i understood this fix here fixed also the setObject class cast exception. iobroker supports typescript, so there should be also a solutions to call the setObject() with typescript. Ok i am waiting for an another unfriendly comment/answer

**Comment by uwe72** [comment]
> Stop spamming every issue please. Ask in the forum.

i solved it by myself. Thanks for your great support. iobroker is a extremly great platform but some of the responsible developers are just not acceptable.

**Pull request merged**
