### PR TITLE
Missing Parameter in setState and setStateDelay of callback

### PR DESCRIPTION
**Pull request by robdg80**
callback of setState and setStateDelayed sometimes have a parameter with the error.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
@AlCalzone  Can you check it?

**Comment by AlCalzone** [comment]
Will do!

**Comment by AlCalzone** [comment]
Looks good! Apparently I missed that.

**Comment by GermanBluefox** [comment]
Thanks all!

**Comment by robdg80** [comment]
Thank You!!

**Pull request merged**
