### PR TITLE
patternMatching optimized

### PR DESCRIPTION
**Pull request by soef**
2 times and mor faster

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Does is work? :)

**Comment by soef** [comment]
On my side it works. Befor sending the pull request I'm using a "patternMatching" function witch calls the old and new function and compares the results. On my nearly 200 subscriptions the function results are the same. 

I know this is not a guarantee for a complete functionality. Look at the code and maybe let someone test it.
I also know this function is very important and is sometimes called 10,000 times in a short time.

**Comment by Apollon77** [comment]
Would it possible to enhance the tests for this?!

**Comment by Apollon77** [comment]
Thank you!
tests fail ... it seems that "done" is not called correctly in your newly added testcase. Thank you for checking that.

Ingo

**Comment by Apollon77** [comment]
Sorry, but still failing: 
https://travis-ci.org/ioBroker/ioBroker.javascript/jobs/260976708#L1538

**Comment by Apollon77** [comment]
it's getting green now :-)

**Comment by Apollon77** [comment]
@GermanBluefox: I would let the merge up to you :-) maybe something to include in 3.4.1 to not block 3.4.0 because of new admin and allow rollbacks

**Pull request merged**
