### PR TITLE
Replace module "request" completely

### PR DESCRIPTION
**Pull request by GermanBluefox**

### CODE REVIEW

**Comment by foxriver76** [comment]
So are all request calls are automatically replaced in user scripts? What will happen to the `require` calls in script, will it be automatically ignored? As now request is no longer a prod dep this could cause crashes.

**Comment by GermanBluefox** [comment]
> So are all request calls are automatically replaced in user scripts? What will happen to the `require` calls in script, will it be automatically ignored? As now request is no longer a prod dep this could cause crashes.

Yes, that's correct. Previously, "request" was automatically available for users, so there was no need to write `const request = require("request");`. Now, if users included unnecessary require calls, it could potentially cause crashes since "request" is no longer a production dependency.

**Comment by foxriver76** [comment]
Should we maybe add some logic to prevent too much trouble? Like if someone requires request, and all require calls fail (js-c v6 import + classic require -> then simply ignore as it is provided by our implementation) or do you see anything blocking this?

**Comment by GermanBluefox** [comment]
> Should we maybe add some logic to prevent too much trouble? Like if someone requires request, and all require calls fail (js-c v6 import + classic require -> then simply ignore as it is provided by our implementation) or do you see anything blocking this?

Monkeypatching of "require" and import?? I think, it is too much

**Comment by GermanBluefox** [comment]
request should not be used till april 2024, so the PR is useless

**Pull request closed without merging**
