### PR TITLE
Update javascript.js

### PR DESCRIPTION
**Pull request by paul53**
Change compareTime() if startTime > endTime

### CODE REVIEW

**Comment by GermanBluefox** [comment]
I cannot understand the change.
What will,  happen if I want to check the time between 23:00 and 1:00?

Your code will return
 !(23:30 >= 1:00 && 23:30 < 23:00) true
!(22:00 >= 1:00 && 22:00 >= 23:00) true

**Comment by paul53** [comment]
between startTime > endTime:
!(23:30 >= 1:00 && 23:30 < 23:00) true
!(22:00 >= 1:00 && 22:00 < 23:00) false

**Comment by GermanBluefox** [comment]
You may not to mix up the start and end time.
We are talking here really about non mixed time and of course the time between 10:00 and 11:00 (just 1 hour) is not the same as 11:00 and 10:00 (23 hours).

```
In your case "if 2017.04.03 23:30 is between 23:00 and 1:00"
!(2017.04.03T23:30 >= 2017.04.03T1:00 && 2017.04.03T23:30 < 2017.04.03T23:00) true
error
!(2017.04.03T22:00 >= 2017.04.03T1:00 && 2017.04.03T22:00 < 2017.04.03T23:00) true
!(2017.04.03T00:30 >= 2017.04.03T1:00 && 2017.04.03T00:30 < 2017.04.03T23:00) true
error
!(2017.04.04T00:30 >= 2017.04.04T1:00 && 2017.04.04T00:30 < 2017.04.04T23:00) true

```
```
My case "if 23:30 is between 23:00 and 1:00"
2017.04.03T23:00 <= 2017.04.03T23:30 && 2017.04.03T23:30 < 2017.04.04T1:00 true
2017.04.03T23:00 <= 2017.04.03T23:30 && 2017.04.03T22:00 < 2017.04.04T1:00 false
2017.04.03T23:00 <= 2017.04.03T00:30 && 2017.04.03T00:30 < 2017.04.04T1:00 false
error
2017.04.04T23:00 <= 2017.04.04T00:30 && 2017.04.04T00:30 < 2017.04.04T1:00 true
```

So both implementations are erroneous and one of them must be fixed.

**Comment by GermanBluefox** [comment]
Can you fix it like here?
http://stackoverflow.com/questions/25954510/check-if-current-time-is-between-2-times-but-also-check-for-nights-as-the-day

**Comment by paul53** [comment]
Skript (getestet):

var start = new Date(2017,04,03,23,0).getTime();
var end = new Date(2017,04,03,1,0).getTime();

var time = new Date(2017,04,03,23,30).getTime();
log(!(time >= end && time < start));  // true

time = new Date(2017,04,03,22,0).getTime();
log(!(time >= end && time < start));  // false

time = new Date(2017,04,03,0,30).getTime();
log(!(time >= end && time < start));  // true

start = new Date(2017,04,04,23,0).getTime();
end = new Date(2017,04,04,1,0).getTime();
time = new Date(2017,04,04,0,30).getTime();
log(!(time >= end && time < start));  // true


Kann keinen Fehler erkennen !


Am 03.04.2017 um 14:31 schrieb GermanBluefox:

**Comment by paul53** [comment]
Kann es sein, dass für time eine String-Aufbereitung fehlt ? Etwa so:

                if (time && typeof time !== 'object') {
                    if (time.indexOf(' ') === -1 && time.indexOf('T') === -1) {
                        var parts = time.split(':');
                        time = new Date();
                        time.setHours(parseInt(parts[0], 10));
                        time.setMinutes(parseInt(parts[1], 10));
                        time.setMilliseconds(0);

                        if (parts.length === 3) {
                            time.setSeconds(parseInt(parts[2], 10));
                        } else {
                            time.setSeconds(0);
                        }
                    } else {
                        time = new Date(time);
                    }
                } else if (!time) {
                    time = new Date();
                    time.setMilliseconds(0);
                }
                time = time.getTime();

**Comment by GermanBluefox** [comment]
time, kann nicht ohne Datum sein.

**Comment by GermanBluefox** [comment]
Es geht darum, dass man start und end ohne Datum eingeben kann:

`compareTime('23:00', '01:00', 'between', new Date());`

und dann werden die tests nicht gehen.

**Comment by GermanBluefox** [comment]
teste bitte so was


`compareTime('23:00', '01:00', 'between', new Date(2017,04,03,23,30)); => muss true`
`compareTime('23:00', '01:00', 'between', new Date(2017,04,04,00,30)); => muss true`
`compareTime('23:00', '01:00', 'between', new Date(2017,04,03,22,30)); => muss false`
`compareTime('23:00', '01:00', 'between', new Date(2017,04,03,02,30)); => muss false`
`compareTime('23:00', '01:00', 'between', new Date(2017,04,04,00,30)); => muss true am 04 Apr`

**Comment by paul53** [comment]
Die Tests funktionieren nur, wenn man start und end ohne Datum eingibt. Deshalb sollte man ein Flag setzen, ob endTime ohne Datum ist und das Flag zusätzlich testen.
                var noenddate = false;
                if (endTime && typeof endTime === 'string') {
                    if (endTime.indexOf(' ') === -1 && endTime.indexOf('T') === -1) {
                        noenddate = true;
...
                if (operation === 'between' && endTime) {
                    if (startTime > endTime && noenddate) return !(time >= endTime && time < startTime);
                    else return time >= startTime && time < endTime;
                } else if (operation === 'not between' && endTime) {
                    if (startTime > endTime && noenddate) return time >= endTime && time < startTime;

**Comment by paul53** [comment]
Habe eine Testfunktion compTime() verwendet, die die Änderungen inkl. noenddate enthält und das Ergebnis stimmt (Monat muss übrigens -1: April = 03):

log(compTime('23:00','01:00','between', new Date(2017,03,03,23,30)));  // true
log(compTime('23:00','01:00','between', new Date(2017,03,03,0,30)));  // true
log(compTime('23:00','01:00','between', new Date(2017,03,03,22,30))); // fasle
log(compTime('23:00','01:00','between', new Date(2017,03,03,2,30)));  // false
log(compTime('23:00','01:00','between', new Date(2017,03,04,0,30)));  // true

**Comment by GermanBluefox** [comment]
Kannst dz das implementieren?

**Comment by paul53** [comment]
Ich habe die Variable _daily_ im pull request hinzugefügt.

**Pull request merged**
