### PR TITLE
New Block: Multiline Text

### PR DESCRIPTION
**Pull request by ThomasPohl**
Adds a block that supports multiline text. That is very useful when sending push notification e.g. via telegram.

### CODE REVIEW

**Comment by ThomasPohl** [comment]
Seems like a timeout-issue.
Is such a multiline block interesting for the project?

**Comment by GermanBluefox** [comment]
Can you provide the screenshot? What is changed?

**Comment by ThomasPohl** [comment]
A new block for multiline text is added in the Text menu:

image

image

**Comment by GermanBluefox** [comment]
Thank you

**Pull request merged**
