### PR TITLE
update blockly to current version

### PR DESCRIPTION
**Pull request by jogibear9988**
there is still one issue wich needs to be fixed

### CODE REVIEW

**Comment by jogibear9988** [comment]
for example insertion markers are supported with this release, test them here: https://rachel-fenichel.github.io/blockly/tests/playground.html

**Comment by GermanBluefox** [comment]
Hm... 
Thank you for PR. 
I tried yet a couple of times to update, but some of the own blocks were then broken.
I need a time to check it.

**Comment by jogibear9988** [comment]
@GermanBluefox now it should work

**Comment by GermanBluefox** [comment]
@jogibear9988 It looks good, but you updated the wrong (generated) files.
Can you apply your changes here: https://github.com/ioBroker/ioBroker.javascript/tree/master/src/public/google-blockly

please ?

**Comment by jogibear9988** [comment]
fixed

**Comment by Apollon77** [comment]
with this and all the stuff we should do an 4.1 :-)

**Comment by AlCalzone** [comment]
Yes this goes past just fixes and deserves a minor version

**Comment by GermanBluefox** [comment]
Super. Thank you!

**Pull request merged**
