### PR TITLE
Use custom TypeScript transformer to enable top-level await with imports

### PR DESCRIPTION
**Pull request by AlCalzone**
TypeScript code is now no longer manipulated using simple string concatenation. Instead the source code is parsed into an AST, all import statements are moved to the top, the other statements are wrapped in an IIAFE (`(async () => { ... })();`) and an empty `export {}`  statement is appended at the bottom.

fixes: #672 
fixes: #677 

A further improvement would be creating a source map and somehow using it to map errors to the actual line numbers - but I haven't figured that one out yet.

### CODE REVIEW

**Comment by agross** [comment]
Thank you, just tested this. Unfortunately, this doesn't work with global scripts. All the types defined in the global script are inaccessible to the real scripts.

**Comment by AlCalzone** [comment]
Can you please show me a script object for a global script (`script.js.global.xyz`) with such a problem? I might have to move a few more things outside the `async` method.

**Comment by agross** [comment]
Knock yourself out:

https://github.com/agross/iobroker-scripts/blob/master/0/Automation/HomeMatic_Shutters.ts#L31
https://github.com/agross/iobroker-scripts/blob/master/0/global/Object_Creator.ts

**Comment by AlCalzone** [comment]
Can you try https://github.com/ioBroker/ioBroker.javascript/tarball/more-TLA-fixes please?

**Pull request merged**
