### PR TITLE
Support onFile changes

### PR DESCRIPTION
**Pull request by GermanBluefox**

### CODE REVIEW

**Review by AlCalzone — COMMENTED** [review]
The onFile/offFile methods should be added to javascript.d.ts too.

**Comment by GermanBluefox** [comment]
> javascript.d.ts

Done

**Comment by AlCalzone** [comment]
We should make the onFile callback in two variants and choose the correct one with overloads in the type declaration. I can do that tomorrow.

**Comment by AlCalzone** [comment]
I would do the following changes to the type declarations to make sure the data and mimeType arguments have the correct type when withFile is known to be true or false:
```patch
diff --git a/lib/javascript.d.ts b/lib/javascript.d.ts
index 9d534ee..c58976d 100644
--- a/lib/javascript.d.ts
+++ b/lib/javascript.d.ts
@@ -891,7 +891,13 @@ declare global {
 
 		type StateChangeHandler<TOld extends StateValue = any, TNew extends TOld = any> = (obj: ChangedStateObject<TOld, TNew>) => void | Promise<void>;
 
-		type FileChangeHandler = (id: string, fileName: string, size: number, data?: Buffer | string, mimeType?: string) => void | Promise<void>;
+		type FileChangeHandler<WithFile extends boolean> =
+			// Variant 1: WithFile is false, data/mimeType is definitely not there
+			[WithFile] extends [false] ? (id: string, fileName: string, size: number, data?: undefined, mimeType?: undefined) => void | Promise<void>
+			// Variant 2: WithFile is true, data (and mimeType?) is definitely there
+			: [WithFile] extends [true] ? (id: string, fileName: string, size: number, data: Buffer | string, mimeType?: string) => void | Promise<void>
+			// Variant 3: WithFile is not known, data/mimeType might be there
+			: (id: string, fileName: string, size: number, data?: Buffer | string, mimeType?: string) => void | Promise<void>;
 
 		type SetObjectCallback = (err?: string | null, obj?: { id: string }) => void | Promise<void>;
 		type SetObjectPromise = Promise<NonNullCallbackReturnTypeOf<SetObjectCallback>>;
@@ -1298,8 +1304,8 @@ declare global {
 	 * @param withFile If the content of the file must be returned in callback (high usage of memory)
 	 * @param handler Callback: function (id, fileName, size, data, mimeType) {}
 	 */
-	function onFile(id: string, filePattern: string | string[], withFile: boolean, handler: iobJS.FileChangeHandler): any;
-	function onFile(id: string, filePattern: string | string[], handler: iobJS.FileChangeHandler): any;
+	function onFile<WithFile extends boolean>(id: string, filePattern: string | string[], withFile: WithFile, handler: iobJS.FileChangeHandler<WithFile>): any;
+	function onFile(id: string, filePattern: string | string[], handler: iobJS.FileChangeHandler<false>): any;
 
 	/**
 	 * Un-subscribe from the changes of the matched files.
diff --git a/test/lib/JS/testDeclarations.js b/test/lib/JS/testDeclarations.js
index 47aa78f..44d4b64 100644
--- a/test/lib/JS/testDeclarations.js
+++ b/test/lib/JS/testDeclarations.js
@@ -47,4 +47,4 @@ if (state1.ack) {
 $('*').setState(1);
 
 // Repro from #636
-$('*').each(async () => {});
\ No newline at end of file
+$('*').each(async () => {});
diff --git a/test/lib/TS/testDeclarations.ts b/test/lib/TS/testDeclarations.ts
index 8e0b74a..7a62056 100644
--- a/test/lib/TS/testDeclarations.ts
+++ b/test/lib/TS/testDeclarations.ts
@@ -28,7 +28,7 @@ const selected = $('selector');
 selected.getState<number>()!.val.toFixed();
 selected.getBinaryState()!.readInt16BE(0);
 
-schedule({astro: "night"}, () => { });
+schedule({ astro: "night" }, () => { });
 
 // TODO: Add more tests
 
@@ -53,4 +53,22 @@ if (state1.notExist) {
 $("*").setState(1);
 
 // Repro from #636
-$("*").each(async () => {});
\ No newline at end of file
+$("*").each(async () => { });
+
+onFile('vis.0', 'main/*', true, (id, fileName, size, data, mimeType) => {
+	assertTrue<Equals<typeof id, string>>();
+	assertTrue<Equals<typeof fileName, string>>();
+	assertTrue<Equals<typeof size, number>>();
+	assertTrue<Equals<typeof data, string | Buffer>>();
+	assertTrue<Equals<typeof mimeType, string | undefined>>();
+});
+
+onFile('vis.0', 'main/*', false, (id, fileName, size, data, mimeType) => {
+	assertTrue<Equals<typeof data, undefined>>();
+	assertTrue<Equals<typeof mimeType, undefined>>();
+});
+
+onFile('vis.0', 'main/*', Math.random() > 0, (id, fileName, size, data, mimeType) => {
+	assertTrue<Equals<typeof data, string | Buffer | undefined>>();
+	assertTrue<Equals<typeof mimeType, string | undefined>>();
+});
\ No newline at end of file
```

(copy this into a new file called `types.patch` and apply the patch with `git apply types.patch`)

**Comment by GermanBluefox** [comment]
> (copy this into a new file called `types.patch` and apply the patch with `git apply types.patch`)
@AlCalzone 
Done

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
