### PR TITLE
fallback to own request module

### LINKED ISSUE #1649: [Bug]: request funktioniert nicht mehr
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Seit der Version 8.7.2 ist kein request mehr möglich.

 Es gibt nur eine error Ausgabe.

### iobroker.current.log (in debug mode!)

<html><body>

javascript.0 | 143315 | 2024-07-26 10:59:11.821 | error | script.js.Sonnenschutz.Rollo1: TypeError: require(...) is not a function     at Object.<anonymous> (script.js.Sonnenschutz.Rollo1:19:23)     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:38)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:645:29)     at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11053:62)     at processImmediate (node:internal/timers:476:21)
-- | -- | -- | -- | --
javascript.0 | 143315 | 2024-07-26 10:59:11.820 | error | at processImmediate (node:internal/timers:476:21)
javascript.0 | 143315 | 2024-07-26 10:59:11.819 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11053:62)
javascript.0 | 143315 | 2024-07-26 10:59:11.819 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:645:29)
javascript.0 | 143315 | 2024-07-26 10:59:11.819 | error | at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:38)
javascript.0 | 143315 | 2024-07-26 10:59:11.818 | error | at Object.<anonymous> (script.js.Sonnenschutz.Rollo1:18:5)
javascript.0 | 143315 | 2024-07-26 10:59:11.818 | error | at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:548:32)
javascript.0 | 143315 | 2024-07-26 10:59:11.817 | error | at require (node:internal/modules/helpers:177:18)
javascript.0 | 143315 | 2024-07-26 10:59:11.817 | error | at Module.require (node:internal/modules/cjs/loader:1231:19)
javascript.0 | 143315 | 2024-07-26 10:59:11.816 | error | script.js.Sonnenschutz.Rollo1: Error: Cannot find module '@iobroker-javascript.0/request'
javascript.0 | 143315 | 2024-07-26 10:59:11.809 | error | script.js.Sonnenschutz.Rollo1: TypeError: require(...) is not a function     at Object.<anonymous> (script.js.Sonnenschutz.Rollo1:19:23)     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:38)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:645:29)     at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11053:62)     at processImmediate (node:internal/timers:476:21)
javascript.0 | 143315 | 2024-07-26 10:59:11.807 | error | at processImmediate (node:internal/timers:476:21)
javascript.0 | 143315 | 2024-07-26 10:59:11.807 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11053:62)
javascript.0 | 143315 | 2024-07-26 10:59:11.806 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:645:29)
javascript.0 | 143315 | 2024-07-26 10:59:11.806 | error | at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:38)
javascript.0 | 143315 | 2024-07-26 10:59:11.806 | error | at Object.<anonymous> (script.js.Sonnenschutz.Rollo1:18:5)
javascript.0 | 143315 | 2024-07-26 10:59:11.805 | error | at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:548:32)
javascript.0 | 143315 | 2024-07-26 10:59:11.805 | error | at require (node:internal/modules/helpers:177:18)
javascript.0 | 143315 | 2024-07-26 10:59:11.805 | error | at Module.require (node:internal/modules/cjs/loader:1231:19)
javascript.0 | 143315 | 2024-07-26 10:59:11.804 | error | script.js.Sonnenschutz.Rollo1: Error: Cannot find module '@iobroker-javascript.0/request'
javascript.0 | 143315 | 2024-07-26 10:59:11.798 | warn | script.js.Sonnenschutz.Rollo1: request package is deprecated - please use httpGet (or a stable lib like axios) instead!
javascript.0 | 143315 | 2024-07-26 10:59:00.048 | info | script.js.TOOLS.Mondstate: Mond: Elevation: 8.4°
javascript.0 | 143315 | 2024-07-26 10:59:00.048 | info | script.js.TOOLS.Mondstate: Mond: Azimut: 265.1°
javascript.0 | 143315 | 2024-07-26 10:59:00.047 | info | script.js.TOOLS.Mondstate: Sonne: Elevation: 47°
javascript.0 | 143315 | 2024-07-26 10:59:00.046 | info | script.js.TOOLS.Mondstate: Sonne: Azimut: 124.9°

</body>
</html>

### Version of nodejs

v18.20.4

### Version of ioBroker js-controller

v6.0.9

### Version of adapter

v8.7.2

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1649

### CODE REVIEW

**Review by Apollon77 — APPROVED** [review]

**Comment by klein0r** [comment]
With that solution, suncalc2 will be the next issue (`suncalc` is mapped by default to suncalc2)

https://github.com/ioBroker/ioBroker.javascript/blob/e670ecb595e67a2dc3c9c99a8db8b09368ebe98d/main.js#L41

https://github.com/ioBroker/ioBroker.javascript/blob/e670ecb595e67a2dc3c9c99a8db8b09368ebe98d/package.json#L55

**Comment by foxriver76** [comment]
If all these modules are just there for being provided by default and not used by javascript directly (idk?) then we should maybe just push them to the list of additional node modules @klein0r

**Comment by klein0r** [comment]
suncalc2 is used by javascript directly. But a lot of users built their own scripts and require that module.

**Comment by foxriver76** [comment]
hm yes then a list instead of just `request` hardcoded? If you have an overview it would be great if you could provide a list or even implement the changes. Or really in the catch try it without the adapter identifier..

**Comment by klein0r** [comment]
> Or really in the catch try it without the adapter identifier..

I would prefer that. Sounds like a good fallback.

**Pull request merged**
