### PR TITLE
add description to 'on' parameter 'value'

### PR DESCRIPTION
**Pull request by twonky4**

### CODE REVIEW

**Comment by AlCalzone** [comment]
> If the `value` parameter is set in combination with state id as the second parameter, on any change the state will filled with the `value`.
> ```js
> on('stateId1', 'stateId2', 'triggered');
> setState('stateId1', 'new value');
> 
> // stateId2 will be set to 'triggered'.
> ```

I don't believe this is intended behavior and as such should either 
* be documented with a warning or 
* be fixed and not documented as all.

@GermanBluefox What do you think? Is this intended or a bug?

**Comment by GermanBluefox** [comment]
Is it still not ready?

**Comment by AlCalzone** [comment]
@GermanBluefox I think that behavior is unintended or a bug like I wrote in the comment above. But I’m not sure and that’s why I asked you to take a look.

**Comment by Apollon77** [comment]
I could find usecases for the behavior ... so why it should not be intended?!

**Comment by AlCalzone** [comment]
Seems weird that the state gets overwritten every time with the third param but that’s just my opinion.

**Comment by GermanBluefox** [comment]
It is the following use case:
If the button is pressed down or "unpressed", switch the light ON.

**Comment by Apollon77** [comment]
My use case is: assume you have a textual field and want to trigger a button when it changes. This would allow that

**Comment by AlCalzone** [comment]
Okay that makes sense. I’ll have to check if that overload is implemented in the typings already.

**Pull request merged**
